# Groups the changelog that the Release workflow generates for each GitHub release
changelog:
    categories:
        - title: Changes
          labels: ['*']
          exclude:
              authors: ['dependabot', 'dependabot[bot]']
        - title: Dependency updates
          labels: ['*']
